version: 1

project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: .lazycat-build/myduck-server.lpk
  target_arch: amd64

update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: myduckserver

build:
  run_buildscript: false

images:
  - id: myduckserver
    target: service
    service: myduckserver
    source: apecloud/myduckserver
    channel: stable
    sort: semver
    tag_regex: '^v?\d+\.\d+\.\d+$'
    delivery:
      mode: lazycat

stores:
  official:
    enabled: true
    skip_if_version_exists: true
    changelog_locales: [zh, en]
  private:
    enabled: true
    skip_if_version_exists: true
    name: MyDuck Server
    summary: 基于DuckDB的MySQL、PostgreSQL数据库服务
