application:
  subdomain: myduck-server
  background_task: true
  multi_instance: false
  upstreams:
    - location: /
      backend: file:///lzcapp/pkg/content/usage.html
  ingress:
    - protocol: tcp
      port: 3306
      service: myduckserver
    - protocol: tcp
      port: 5432
      service: myduckserver
services:
  myduckserver:
    # upstream: apecloud/myduckserver:v0.3.0
    image: registry.lazycat.cloud/czyt/apecloud/myduckserver:d16184bc095dc75d
    binds:
      - /lzcapp/var/data:/home/admin/data
    setup_script: |
      if [ -z "$(find /home/admin/data/myduck.db -mindepth 1 -maxdepth 1)" ]; then
          echo "myduck.db not found, copying from pkg to user directory"
          cp  /lzcapp/pkg/content/myduck.db  /home/admin/data/
      fi
